version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: traveltales-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    restart: unless-stopped
    networks:
      - traveltales-network
    volumes:
      - ./backend:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 30s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: traveltales-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - traveltales-network
    depends_on:
      backend:
        condition: service_healthy

networks:
  traveltales-network:
    driver: bridge
