version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3001:5000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend/database.sqlite:/app/database.sqlite
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_BASE_URL=http://backend:5000/api
    depends_on:
      - backend
    restart: unless-stopped 